import React from 'react'

const about = () => {
  return (
    <div>
      I am your about 
    </div>
  )
}

export default about

export const metadata = {
    title: "About",
    description: "Generated by create next app",
};
