import React from 'react'
import Script from 'next/script'
import Image from 'next/image'
const  contact = () => {
  return (
    <div>
      <Script>
        {`alert('Welcome to the Contact page')`}
      </Script>
      Your Cantact info
      <Image
      unoptimized
      src="https://media.istockphoto.com/id/1981164982/photo/beautiful-view-of-blue-sea-or-ocean-by-the-white-beach-in-summer-okinawa-in-japan-nobody.webp?b=1&s=170667a&w=0&k=20&c=uPnuOPbvDEN_WTY_704z2DKItQvhkqMjHuEn1Yz9tPk="
      width={500}
      height={500}
      alt="Picture of the author"
    />
    
      
    </div>
  )
}

export default contact

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

